### ISSUE TITLE
Fix error message for bad json file

### ISSUE THREAD

**Issue by SemenMartynov** [Lorismelik/JSON_validator#5]
Expected:

{
 "errorCode"  : 12345,
 "errorMessage" : ["verbose, plain language description of the problem with hints about how to fix it]",
 "errorPlace" : ["highlight the point where error has occurred"],
 "resource"   : ["filename"],
 "request-id" : ["the request id generated by the API for easier tracking of errors"],
}

Received:

`Unterminated array at line 1 column 2943 path $.web-app.servlet[4]`

**Comment by SemenMartynov** [comment]
`resource` field should contain uploaded file name. Please implement PUT method for this.

```
$ curl -s --data-binary @bad.json http://localhost                                 
{
  "errorPlace": " line 1 column 2943 path $.web-app.servlet[4]",
  "resource": "filename",
  "errorMessage": "Unterminated array",
  "errorCode": "12345",
  "request-id": "12345"
}

```
```
$ curl --upload-file bad.json http://localhost                                    
$
```

**Comment by Lorismelik** [comment]
Sorry, made a mistake in name of commit. Link: 0e3b425

**Comment by SemenMartynov** [comment]
Do you know how to fix git history?

---


I can't get server response now...

```
$ curl --upload-file good.json http://localhost                                    
$ curl --upload-file bad.json http://localhost                                     
$ curl -s --data-binary @good.json http://localhost
$ curl -s --data-binary @bad.json http://localhost

```
Nothing happens...

**Comment by Lorismelik** [comment]
@SemenMartynov  I changed request to 
`curl  --form "file=@filename" localhost:80`

**Comment by SemenMartynov** [comment]
It does not correspond to the task conditions.

**Comment by SemenMartynov** [comment]
Please update your project documentation too.
