### ISSUE TITLE
Task2

### ISSUE THREAD

**Issue by SemenMartynov** [Lorismelik/JSON_validator#6]
After you solve all the opened issues go ahead and implement task 2.

**Comment by SemenMartynov** [comment]
Any updates?

**Comment by SemenMartynov** [comment]
I don't see any updates in master branch or project documentation.

**Comment by SemenMartynov** [comment]
`build` -- to `.gitignore` and remove from repo.

**Comment by Lorismelik** [comment]
@SemenMartynov  i did it some minutes ago

**Comment by SemenMartynov** [comment]
.. and `.gradle` too!))
